### Cleaning the MVP dataset

In [258]:
import pandas as pd

In [259]:
mvps = pd.read_csv("mvps.csv")

In [260]:
#Keeping only the neccessary columns
mvps = mvps[["Player", "Year", "Pts Won", "Pts Max", "Share"]]

In [261]:
mvps

              Player  Year  Pts Won  Pts Max  Share
0     Michael Jordan  1991      891      960  0.928
1      Magic Johnson  1991      497      960  0.518
2     David Robinson  1991      476      960  0.496
3    Charles Barkley  1991      222      960  0.231
4        Karl Malone  1991      142      960  0.148
..               ...   ...      ...      ...    ...
515  Anthony Edwards  2025       12     1000  0.012
516    Stephen Curry  2025        2     1000  0.002
517    Jalen Brunson  2025        1     1000  0.001
518     James Harden  2025        1     1000  0.001
519      Evan Mobley  2025        1     1000  0.001

[520 rows x 5 columns]

### Cleaning the player stats dataset

In [262]:
players = pd.read_csv("PlayerStats.csv")

In [263]:
players

,Unnamed: 0,Rk,Player,Age,Team,Pos,G,GS,MP,FG,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,0,1,Michael Jordan,27,CHI,SG,82,82,37.0,12.1,...,4.6,6.0,5.5,2.7,1.0,2.5,2.8,31.5,"MVP-1,DPOY-7,AS,NBA1,DEF1",1991
1,1,2,Karl Malone,27,UTA,PF,82,82,40.3,10.3,...,8.9,11.8,3.3,1.1,1.0,3.0,3.3,29.0,"MVP-5,AS,NBA1",1991
2,2,3,Bernard King,34,WSB,SF,64,64,37.5,11.1,...,3.2,5.0,4.6,0.9,0.3,4.0,2.9,28.4,"MVP-16,AS,NBA3",1991
3,3,4,Charles Barkley,27,PHI,SF,67,67,37.3,9.9,...,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,"MVP-4,AS,NBA1",1991
4,4,5,Patrick Ewing,28,NYK,C,81,81,38.3,10.4,...,8.8,11.2,3.0,1.0,3.2,3.6,3.5,26.6,"MVP-11,DPOY-7,AS,NBA2",1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21335,766,566,Jahlil Okafor,29,IND,C,1,0,3.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,2025
21336,767,567,Zyon Pullin,23,MEM,SG,3,0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2025
21337,768,568,Isaiah Stevens,24,MIA,PG,3,0,2.0,0.0,...,0.7,0.7,0.0,0.3,0.0,0.0,0.0,0.0,NaN,2025
21338,769,569,Terry Taylor,25,SAC,PF,3,0,2.0,0.0,...,0.0,0.3,0.7,0.0,0.0,0.0,0.0,0.0,NaN,2025
21339,770,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025

In [264]:
#Removing unneeded columns
del players["Unnamed: 0"]
del players["Rk"]
del players["Awards"]

In [265]:
#Some players have multiple rows for the same season since they played for different teams
#To handle this i will group by player and year and keep only one row per season which will be the average of their season stats
#Denoted in the dataset as 3TM

players.groupby(["Player", "Year"])

def singlerow(df):
    if df.shape[0]==1:
        return df
    else:
        row = df[df["Team"] == "3TM"]
        row["Team"] = df.iloc[-1,:]["Team"]
        return row

players = players.groupby(["Player", "Year"]).apply(singlerow)

/var/folders/2s/ccdjm_pd3739b6j36vkcntfw0000gn/T/ipykernel_73980/20886209.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  players = players.groupby(["Player", "Year"]).apply(singlerow)

In [266]:
players.head(50)

                                 Player Age Team Pos   G  GS    MP   FG   FGA  \
Player        Year
A.C. Green    1991 185       A.C. Green  27  LAL  PF  82  21  26.4  3.1   6.6
              1992 558       A.C. Green  28  LAL  PF  82  53  35.4  4.7   9.8
              1993 1051      A.C. Green  29  LAL  PF  82  55  34.4  4.6   8.6
              1994 1488      A.C. Green  30  PHO  PF  82  55  34.5  5.7  11.3
              1995 2053      A.C. Green  31  PHO  SF  82  52  32.8  3.8   7.5
              1996 2643      A.C. Green  32  PHO  SF  82  36  25.8  2.6   5.4
              1998 3820      A.C. Green  34  DAL  PF  82  68  32.3  3.0   6.5
              1999 4448      A.C. Green  35  DAL  PF  50  35  18.5  2.2   5.1
              2000 4987      A.C. Green  36  LAL  PF  82  82  23.5  2.1   4.7
              2001 5555      A.C. Green  37  MIA  PF  82   1  17.2  1.8   4.0
A.J. Bramlett 2000 5167   A.J. Bramlett  23  CLE   C   8   0   7.6  0.5   2.6
A.J. English  1991 190     A.J. English  23  WSB  SG  70  12  20.6  3.6   8.2
              1992 602     A.J. English  24  WSB  SG  81   6  20.6  4.5  10.4
A.J. Green    2023 19605     A.J. Green  23  MIL  SG  35   1   9.9  1.5   3.6
              2024 20292     A.J. Green  24  MIL  SG  56   0  11.0  1.5   3.5
              2025 20922     A.J. Green  25  MIL  SG  73   7  22.7  2.5   5.8
A.J. Guyton   2001 5469     A.J. Guyton  22  CHI  PG  33   8  19.1  2.4   5.8
              2002 6052     A.J. Guyton  23  CHI  PG  45   6  13.5  2.0   5.4
              2003 6777     A.J. Guyton  24  GSW  PG   2   0   4.5  0.0   2.0
A.J. Hammons  2017 15320   A.J. Hammons  24  DAL   C  22   0   7.4  0.8   1.9
A.J. Lawson   2024 20409    A.J. Lawson  23  DAL  SG  42   0   7.4  1.3   2.9
              2025 20838    A.J. Lawson  24  TOR  SG  26   2  18.7  3.1   7.3
A.J. Price    2010 10673     A.J. Price  23  IND  PG  56   2  15.4  2.6   6.3
              2011 11316     A.J. Price  24  IND  PG  50   0  15.9  2.3   6.4
              2012 12045     A.J. Price  25  IND  PG  44   1  12.9  1.3   4.0
              2013 12458     A.J. Price  26  WAS  PG  57  22  22.4  2.8   7.2
              2014 13406     A.J. Price  27  MIN  SG  28   0   3.5  0.7   1.6
              2015 13900     A.J. Price  28  PHO  PG  26   0  12.5  2.0   5.3
A.J. Wynder   1991 417      A.J. Wynder  26  BOS  PG   6   0   6.5  0.5   2.0
AJ Griffin    2023 19362     AJ Griffin  19  ATL  SF  72  12  19.5  3.4   7.4
              2024 20454     AJ Griffin  20  ATL  SF  20   0   8.6  0.9   3.1
Aaron Brooks  2008 9497    Aaron Brooks  23  HOU  PG  51   0  11.9  1.8   4.4
              2009 9941    Aaron Brooks  24  HOU  PG  80  35  25.0  4.0   9.8
              2010 10401   Aaron Brooks  25  HOU  PG  82  82  35.6  7.0  16.2
              2015 13614   Aaron Brooks  30  CHI  PG  82  21  23.0  4.2  10.0
              2016 14421   Aaron Brooks  31  CHI  PG  69   0  16.1  2.7   6.8
              2017 15173   Aaron Brooks  32  IND  PG  65   0  13.8  1.9   4.6
              2018 15966   Aaron Brooks  33  MIN  PG  32   1   5.9  0.9   2.2
Aaron Gordon  2015 13896   Aaron Gordon  19  ORL  PF  47   8  17.0  2.0   4.4
              2016 14340   Aaron Gordon  20  ORL  PF  78  37  23.9  3.5   7.4
              2017 14863   Aaron Gordon  21  ORL  SF  80  72  28.7  4.9  10.8
              2018 15421   Aaron Gordon  22  ORL  PF  58  57  32.9  6.5  14.9
              2019 16145   Aaron Gordon  23  ORL  PF  78  78  33.8  6.0  13.4
              2020 16923   Aaron Gordon  24  ORL  PF  62  62  32.5  5.4  12.4
              2022 18346   Aaron Gordon  26  DEN  PF  75  75  31.7  5.8  11.1
              2023 19180   Aaron Gordon  27  DEN  PF  68  68  30.2  6.3  11.2
              2024 19925   Aaron Gordon  28  DEN  PF  73  73  31.5  5.5   9.8
              2025 20686   Aaron Gordon  29  DEN  PF  51  42  28.4  5.2   9.7
Aaron Gray    2008 9545      Aaron Gray  23  CHI   C  61   1  10.0  1.7   3.3
              2009 10210     Aaron Gray  24  CHI   C  56  18  12.8  1.4   3.0

                           FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  \
Player        Year              ...
A.C. Green    1991 185    .476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2  1.4
              1992 558    .476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4  1.7
              1993 1051   .537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4  1.8
              1994 1488   .502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2  1.7
              1995 2053   .504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4  1.8
              1996 2643   .484  ...  2.0  4.7  6.8  0.9  0.5  0.3  1.0  1.7
              1998 3820   .453  ...  2.7  5.5  8.1  1.5  1.0  0.3  0.8  1.9
              1999 4448   .422  ...  1.6  2.9  4.6  0.5  0.6  0.2  0.4  1.4
              2000 4987   .447  ...  2.0  4.0  5.9  1.0  0.6  0.2  0.6  1.5
              2001 5555   .444  ...  1.3  2.5  3.8  0.5  0.4  0.1  0.5  1.5
A.J. Bramlett 2000 5167   .190  ...  1.5  1.3  2.8  0.0  0.1  0.0  0.4  1.6
A.J. English  1991 190    .439  ...  0.9  1.2  2.1  2.5  0.4  0.2  1.6  1.8
              1992 602    .433  ...  0.9  1.2  2.1  1.8  0.4  0.1  1.1  2.0
A.J. Green    2023 19605  .424  ...  0.2  1.1  1.3  0.6  0.2  0.0  0.3  0.9
              2024 20292  .423  ...  0.2  1.0  1.1  0.5  0.2  0.1  0.2  0.9
              2025 20922  .429  ...  0.2  2.1  2.4  1.5  0.5  0.1  0.5  2.2
A.J. Guyton   2001 5469   .406  ...  0.3  0.8  1.1  1.9  0.3  0.2  0.7  1.1
              2002 6052   .361  ...  0.3  0.7  1.0  1.8  0.2  0.2  0.8  0.5
              2003 6777   .000  ...  0.0  0.0  0.0  1.0  0.5  0.0  0.5  0.0
A.J. Hammons  2017 15320  .405  ...  0.4  1.3  1.6  0.2  0.0  0.6  0.5  1.0
A.J. Lawson   2024 20409  .446  ...  0.3  0.9  1.2  0.5  0.2  0.1  0.3  0.5
              2025 20838  .421  ...  0.8  2.5  3.3  1.2  0.5  0.2  0.6  1.7
A.J. Price    2010 10673  .410  ...  0.2  1.4  1.6  1.9  0.6  0.1  1.1  0.9
              2011 11316  .356  ...  0.3  1.1  1.4  2.2  0.6  0.0  1.1  1.2
              2012 12045  .339  ...  0.3  1.1  1.4  2.0  0.5  0.0  0.7  0.7
              2013 12458  .390  ...  0.4  1.6  2.0  3.6  0.6  0.1  1.1  1.3
              2014 13406  .413  ...  0.0  0.3  0.4  0.5  0.0  0.0  0.3  0.2
              2015 13900  .372  ...  0.2  1.0  1.2  1.8  0.3  0.0  0.5  0.6
A.J. Wynder   1991 417    .250  ...  0.2  0.3  0.5  1.3  0.2  0.0  0.7  0.2
AJ Griffin    2023 19362  .465  ...  0.5  1.6  2.1  1.0  0.6  0.2  0.6  1.2
              2024 20454  .290  ...  0.1  0.8  0.9  0.3  0.1  0.1  0.4  0.3
Aaron Brooks  2008 9497   .413  ...  0.3  0.8  1.1  1.7  0.3  0.1  0.9  1.4
              2009 9941   .404  ...  0.4  1.6  2.0  3.0  0.6  0.1  1.6  1.9
              2010 10401  .432  ...  0.7  2.0  2.6  5.3  0.8  0.2  2.8  2.4
              2015 13614  .421  ...  0.4  1.6  2.0  3.2  0.7  0.2  1.9  2.3
              2016 14421  .401  ...  0.3  1.2  1.5  2.6  0.4  0.1  1.2  1.9
              2017 15173  .403  ...  0.3  0.8  1.1  1.9  0.4  0.1  1.0  1.4
              2018 15966  .406  ...  0.2  0.3  0.5  0.6  0.2  0.0  0.3  0.9
Aaron Gordon  2015 13896  .447  ...  1.0  2.6  3.6  0.7  0.4  0.5  0.8  1.8
              2016 14340  .473  ...  2.0  4.5  6.5  1.6  0.8  0.7  0.8  2.0
              2017 14863  .454  ...  1.5  3.6  5.1  1.9  0.8  0.5  1.1  2.2
              2018 15421  .434  ...  1.5  6.4  7.9  2.3  1.0  0.8  1.8  1.9
              2019 16145  .449  ...  1.7  5.7  7.4  3.7  0.7  0.7  2.1  2.2
              2020 16923  .437  ...  1.7  5.9  7.7  3.7  0.8  0.6  1.6  2.0
              2022 18346  .520  ...  1.7  4.2  5.9  2.5  0.6  0.6  1.8  2.0
              2023 19180  .564  ...  2.4  4.1  6.6  3.0  0.8  0.8  1.4  1.9
              2024 19925  .556  ...  2.4  4.1  6.5  3.5  0.8  0.6  1.4  1.9
              2025 20686  .531  ...  1.6  3.3  4.8  3.2  0.5  0.3  1.4  1.6
Aaron Gray    2008 9545   .505  ...  1.1  1.6  2.8  0.7  0.3  0.3  0.9  1.9
              2009 10210  .485  ...  1.5  2.4  3.9  0.8  0.3  0.3  0.7  2.4

                           PTS  Year
Player        Year
A.C. Green    1991 185     9.1  1991
              1992 558    13.6  1992
              1993 1051   12.8  1993
              1994 1488   14.7  1994
              1995 2053   11.2  1995
              1996 2643    7.5  1996
              1998 3820    7.3  1998
              1999 4448    4.9  1999
              2000 4987    5.0  2000
              2001 5555    4.5  2001
A.J. Bramlett 2000 5167    1.0  2000
A.J. English  1991 190     8.8  1991
              1992 602    10.9  1992
A.J. Green    2023 19605   4.4  2023
              2024 20292   4.5  2024
              2025 20922   7.4  2025
A.J. Guyton   2001 5469    6.0  2001
              2002 6052    5.4  2002
              2003 6777    0.0  2003
A.J. Hammons  2017 15320   2.2  2017
A.J. Lawson   2024 20409   3.2  2024
              2025 20838   9.1  2025
A.J. Price    2010 10673   7.3  2010
              2011 11316   6.5  2011
              2012 12045   3.9  2012
              2013 12458   7.7  2013
              2014 13406   1.6  2014
              2015 13900   5.1  2015
A.J. Wynder   1991 417     2.0  1991
AJ Griffin    2023 19362   8.9  2023
              2024 20454   2.4  2024
Aaron Brooks  2008 9497    5.2  2008
              2009 9941   11.2  2009
              2010 10401  19.6  2010
              2015 13614  11.6  2015
              2016 14421   7.1  2016
              2017 15173   5.0  2017
              2018 15966   2.3  2018
Aaron Gordon  2015 13896   5.2  2015
              2016 14340   9.2  2016
              2017 14863  12.7  2017
              2018 15421  17.6  2018
              2019 16145  16.0  2019
              2020 16923  14.4  2020
              2022 18346  15.0  2022
              2023 19180  16.3  2023
              2024 19925  13.9  2024
              2025 20686  14.7  2025
Aaron Gray    2008 9545    4.3  2008
              2009 10210   3.5  2009

[50 rows x 30 columns]

In [267]:
players.index = players.index.droplevel()

In [268]:
players.index = players.index.droplevel()

In [269]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
185,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991
558,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992
1051,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993
1488,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994
2053,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8431,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.6,1.2,1.8,0.3,0.2,0.1,0.6,1.4,3.3,2006
5999,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002
6509,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003
7735,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005
8357,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006

#### Now we can merge the two datasets

In [270]:
#Here i am combining the MVP and players dataframes on the player and year columns
combined = players.merge(mvps, how= "outer", on= ["Player", "Year"])

In [271]:
combined.head()

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN

In [272]:
#There are many players in our dataframe that didnt recieve any MVP votes so they have NAN, for data cleaning purposes
#I will fill those NANs with zeros because they realistically got no votes

combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [273]:
combined.head()

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0

### Now I will clean the Teams dataset

In [274]:
teams = pd.read_csv("Teams.csv")

In [275]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
6,6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1991,Central Division
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
14,0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,1991,Midwest Division
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
22,8,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,1991,Pacific Division
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings

In [276]:
#From our webscraping there are some rows that are invalid and are just called Midwest Division or Pacific Division

#This basically get rids of any rows where the win column has the word division
teams = teams[~teams["W"].str.contains("Division")]

In [277]:
#Some teams also have asterisks by their names if they made the playoffs so we have to make that consistent

teams["Team"] = teams["Team"].str.replace("*", "", regex= False)

In [278]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings
30,0,51,31,.622,—,106.6,103.0,3.41,1992,Boston Celtics
31,1,51,31,.622,—,101.6,97.7,3.67,1992,New York Knicks
32,2,40,42,.488,11.0,105.4,107.1,-1.54,1992,New Jersey Nets

In [279]:
#Another issue i have to solve is the inconsistent between team names in the combined dataset and the teams dataset

teams["Team"].unique()

array(['Boston Celtics', 'Philadelphia 76ers', 'New York Knicks',
       'Washington Bullets', 'New Jersey Nets', 'Miami Heat',
       'Chicago Bulls', 'Detroit Pistons', 'Milwaukee Bucks',
       'Atlanta Hawks', 'Indiana Pacers', 'Cleveland Cavaliers',
       'Charlotte Hornets', 'San Antonio Spurs', 'Utah Jazz',
       'Houston Rockets', 'Orlando Magic', 'Minnesota Timberwolves',
       'Dallas Mavericks', 'Denver Nuggets', 'Portland Trail Blazers',
       'Los Angeles Lakers', 'Phoenix Suns', 'Golden State Warriors',
       'Seattle SuperSonics', 'Los Angeles Clippers', 'Sacramento Kings',
       'Toronto Raptors', 'Vancouver Grizzlies', 'Washington Wizards',
       'Memphis Grizzlies', 'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

In [280]:
combined["Team"].unique()

array(['LAL', 'PHO', 'DAL', 'MIA', 'CLE', 'WSB', 'MIL', 'CHI', 'GSW',
       'TOR', 'IND', 'WAS', 'MIN', 'BOS', 'ATL', 'HOU', 'ORL', 'DEN',
       'NOH', 'CHO', 'PHI', 'POR', 'OKC', 'UTA', 'SEA', 'NJN', 'LAC',
       'CHA', 'SAC', 'NYK', 'NOP', 'BRK', 'DET', 'SAS', 'MEM', 'CHH',
       'VAN', 'NOK', nan], dtype=object)

In [281]:
#To handle this i will use a dictionary that maps between the nicknames and team names
nicknames = {
    'LAL': 'Los Angeles Lakers',
    'PHO': 'Phoenix Suns',
    'DAL': 'Dallas Mavericks',
    'MIA': 'Miami Heat',
    'CLE': 'Cleveland Cavaliers',
    'WSB': 'Washington Bullets',   # old name
    'WAS': 'Washington Wizards',
    'MIL': 'Milwaukee Bucks',
    'CHI': 'Chicago Bulls',
    'GSW': 'Golden State Warriors',
    'TOR': 'Toronto Raptors',
    'IND': 'Indiana Pacers',
    'MIN': 'Minnesota Timberwolves',
    'BOS': 'Boston Celtics',
    'ATL': 'Atlanta Hawks',
    'HOU': 'Houston Rockets',
    'ORL': 'Orlando Magic',
    'DEN': 'Denver Nuggets',
    'NOH': 'New Orleans Hornets',
    'NOP': 'New Orleans Pelicans',
    'NOK': 'New Orleans/Oklahoma City Hornets',
    'NYK': 'New York Knicks',
    'PHI': 'Philadelphia 76ers',
    'POR': 'Portland Trail Blazers',
    'OKC': 'Oklahoma City Thunder',
    'UTA': 'Utah Jazz',
    'SEA': 'Seattle SuperSonics',
    'NJN': 'New Jersey Nets',
    'BRK': 'Brooklyn Nets',
    'LAC': 'Los Angeles Clippers',
    'SAC': 'Sacramento Kings',
    'DET': 'Detroit Pistons',
    'SAS': 'San Antonio Spurs',
    'MEM': 'Memphis Grizzlies',
    'VAN': 'Vancouver Grizzlies',
    'CHA': 'Charlotte Bobcats',
    'CHO': 'Charlotte Hornets',   # alt code
    'CHH': 'Charlotte Hornets'    # old code
}

In [282]:
combined["Team"] = combined["Team"].map(nicknames)

In [283]:
#Now we will merge our combined dataframe with the team dataframe
stats = combined.merge(teams, how= "outer", on= ["Team", "Year"])

In [284]:
stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,Doc Rivers,29,Atlanta Hawks,PG,79,79,32.7,5.6,12.9,.435,...,0.0,0.00,10.0,43,39,.524,18.0,109.8,109.0,0.72
1,Dominique Wilkins,31,Atlanta Hawks,SF,81,81,38.0,9.5,20.2,.470,...,960.0,0.03,10.0,43,39,.524,18.0,109.8,109.0,0.72
2,Duane Ferrell,25,Atlanta Hawks,SF,78,2,14.9,2.2,4.6,.489,...,0.0,0.00,10.0,43,39,.524,18.0,109.8,109.0,0.72
3,Gary Leonard,23,Atlanta Hawks,C,4,0,2.3,0.0,0.0,NaN,...,0.0,0.00,10.0,43,39,.524,18.0,109.8,109.0,0.72
4,John Battle,28,Atlanta Hawks,SG,79,2,23.6,5.0,10.9,.461,...,0.0,0.00,10.0,43,39,.524,18.0,109.8,109.0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14625,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.466,...,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14626,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.461,...,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14627,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.475,...,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14628,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.474,...,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14629,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.467,...,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [285]:
del stats["Unnamed: 0"]

In [286]:
#A lot of these numerical columns have been stored as strings
stats.dtypes

Player      object
Age         object
Team        object
Pos         object
G           object
GS          object
MP          object
FG          object
FGA         object
FG%         object
3P          object
3PA         object
3P%         object
2P          object
2PA         object
2P%         object
eFG%        object
FT          object
FTA         object
FT%         object
ORB         object
DRB         object
TRB         object
AST         object
STL         object
BLK         object
TOV         object
PF          object
PTS         object
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
W           object
L           object
W/L%        object
GB          object
PS/G        object
PA/G        object
SRS         object
dtype: object

In [287]:
stats = stats.apply(pd.to_numeric, errors= "ignore")
stats.dtypes

/var/folders/2s/ccdjm_pd3739b6j36vkcntfw0000gn/T/ipykernel_73980/1956319287.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  stats = stats.apply(pd.to_numeric, errors= "ignore")

Player      object
Age        float64
Team        object
Pos         object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
W          float64
L          float64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [288]:
#Games back should also be a number I found that the issue is the dash so lets replace it
print(stats["GB"].unique())
stats["GB"] = stats["GB"].str.replace( '—', "0")

['18.0' '29.0' '14.0' '—' '10.0' '26.0' '13.0' '12.0' '2.0' '28.0' '27.0'
 '17.0' '15.0' '33.0' '46.0' '6.0' '22.0' '16.0' '20.0' '21.0' '3.0'
 '11.0' '1.0' '25.0' '19.0' '5.0' '23.0' '12.5' '9.0' '8.0' '4.0' '35.0'
 '31.0' '7.0' '32.0' '41.0' '24.0' '39.0' '45.0' '36.0' '37.0' '38.0'
 '4.5' '30.0' '43.0' '25.5' '44.0' '40.0' '42.0' '2.5' '51.0' '34.0'
 '20.5' '32.5' '48.0' '52.0' '3.5' '56.0' '10.5' '47.0' '11.5' '22.5'
 '1.5' '50.0' '21.5' '18.5' nan]

In [289]:
print(stats["GB"].unique())
stats["GB"] = pd.to_numeric(stats["GB"])

['18.0' '29.0' '14.0' '0' '10.0' '26.0' '13.0' '12.0' '2.0' '28.0' '27.0'
 '17.0' '15.0' '33.0' '46.0' '6.0' '22.0' '16.0' '20.0' '21.0' '3.0'
 '11.0' '1.0' '25.0' '19.0' '5.0' '23.0' '12.5' '9.0' '8.0' '4.0' '35.0'
 '31.0' '7.0' '32.0' '41.0' '24.0' '39.0' '45.0' '36.0' '37.0' '38.0'
 '4.5' '30.0' '43.0' '25.5' '44.0' '40.0' '42.0' '2.5' '51.0' '34.0'
 '20.5' '32.5' '48.0' '52.0' '3.5' '56.0' '10.5' '47.0' '11.5' '22.5'
 '1.5' '50.0' '21.5' '18.5' nan]

In [290]:
#There are multiple league average columns so we will move them from our stats dataframe to another df
league_averages = stats[stats["Player"] == 'League Average']
stats = stats[stats["Player"] != 'League Average']

In [291]:
stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Pts Won,Pts Max,Share,W,L,W/L%,GB,PS/G,PA/G,SRS
0,Doc Rivers,29.0,Atlanta Hawks,PG,79.0,79.0,32.7,5.6,12.9,0.435,...,0.0,0.0,0.000,43.0,39.0,0.524,18.0,109.8,109.0,0.72
1,Dominique Wilkins,31.0,Atlanta Hawks,SF,81.0,81.0,38.0,9.5,20.2,0.470,...,29.0,960.0,0.030,43.0,39.0,0.524,18.0,109.8,109.0,0.72
2,Duane Ferrell,25.0,Atlanta Hawks,SF,78.0,2.0,14.9,2.2,4.6,0.489,...,0.0,0.0,0.000,43.0,39.0,0.524,18.0,109.8,109.0,0.72
3,Gary Leonard,23.0,Atlanta Hawks,C,4.0,0.0,2.3,0.0,0.0,NaN,...,0.0,0.0,0.000,43.0,39.0,0.524,18.0,109.8,109.0,0.72
4,John Battle,28.0,Atlanta Hawks,SG,79.0,2.0,23.6,5.0,10.9,0.461,...,0.0,0.0,0.000,43.0,39.0,0.524,18.0,109.8,109.0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14605,Vince Carter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,1270.0,0.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14609,Chauncey Billups,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.0,1210.0,0.027,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14612,Stephen Jackson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1230.0,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14623,Derrick Rose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,1010.0,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14624,James Harden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1010.0,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Now lets clean the final combined dataset

In [292]:
pd.isnull(stats).sum()

Player        0
Age           7
Team          7
Pos           7
G             7
GS            7
MP            7
FG            7
FGA           7
FG%          75
3P            7
3PA           7
3P%        1947
2P            7
2PA           7
2P%         124
eFG%         75
FT            7
FTA           7
FT%         570
ORB           7
DRB           7
TRB           7
AST           7
STL           7
BLK           7
TOV           7
PF            7
PTS           7
Year          0
Pts Won       0
Pts Max       0
Share         0
W             7
L             7
W/L%          7
GB            7
PS/G          7
PA/G          7
SRS           7
dtype: int64

In [293]:
pd.isnull(stats).sum()

Player        0
Age           7
Team          7
Pos           7
G             7
GS            7
MP            7
FG            7
FGA           7
FG%          75
3P            7
3PA           7
3P%        1947
2P            7
2PA           7
2P%         124
eFG%         75
FT            7
FTA           7
FT%         570
ORB           7
DRB           7
TRB           7
AST           7
STL           7
BLK           7
TOV           7
PF            7
PTS           7
Year          0
Pts Won       0
Pts Max       0
Share         0
W             7
L             7
W/L%          7
GB            7
PS/G          7
PA/G          7
SRS           7
dtype: int64

In [294]:
#These are the players with all null stats but share votes, since they are good players they actually got those MVP votes
#However i dont know why i am getting these rows, it could be because of an improper merge

#It is possible that the pts won, pts max, and share columns are taken from other rows where they should be inputted instead of 0, 
#But since the shares are minimal i am making the decision of just dropping them

stats[stats[["Age","MP","PTS"]].isnull().any(axis=1)]

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Pts Won,Pts Max,Share,W,L,W/L%,GB,PS/G,PA/G,SRS
14591,Dominique Wilkins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1010.0,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14593,Clyde Drexler,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,1050.0,0.003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14605,Vince Carter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,1270.0,0.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14609,Chauncey Billups,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.0,1210.0,0.027,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14612,Stephen Jackson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1230.0,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14623,Derrick Rose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,1010.0,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14624,James Harden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1010.0,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [295]:
#I am going to drop them
stats = stats[stats["Team"].notna()]

In [296]:
#Checking
stats[stats[["Age"]].isnull().any(axis=1)]

Empty DataFrame
Columns: [Player, Age, Team, Pos, G, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, Year, Pts Won, Pts Max, Share, W, L, W/L%, GB, PS/G, PA/G, SRS]
Index: []

[0 rows x 40 columns]

In [297]:
pd.isnull(stats).sum()

Player        0
Age           0
Team          0
Pos           0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          68
3P            0
3PA           0
3P%        1940
2P            0
2PA           0
2P%         117
eFG%         68
FT            0
FTA           0
FT%         563
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [298]:
#Any players with null 3p percentage didnt attempt any 3 pointers, same goes for free throws, and field goal percentage
stats[pd.isnull(stats["3P%"])] [["Player","3PA"]]

                 Player  3PA
3          Gary Leonard  0.0
17         Gary Leonard  0.0
18         Jeff Sanders  0.0
32         Jeff Sanders  0.0
37         Randy Breuer  0.0
...                 ...  ...
14530   Jaime Echenique  0.0
14543    Daniel Gafford  0.0
14557  Vernon Carey Jr.  0.0
14564    Hamidou Diallo  0.0
14580   Jalen McDaniels  0.0

[1940 rows x 2 columns]

In [299]:
#To handle this i will fill the values with 0, this isnt the most correct but since the players don't attempt 3s anyway
#It will play into their MVP voting
columns = ["FT%", "FG%", "3P%", "2P%", "eFG%"]
stats[columns] = stats[columns].fillna(0)

/var/folders/2s/ccdjm_pd3739b6j36vkcntfw0000gn/T/ipykernel_73980/2096841962.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats[columns] = stats[columns].fillna(0)

In [300]:
pd.isnull(stats).sum()

Player     0
Age        0
Team       0
Pos        0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        0
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
Year       0
Pts Won    0
Pts Max    0
Share      0
W          0
L          0
W/L%       0
GB         0
PS/G       0
PA/G       0
SRS        0
dtype: int64

In [301]:
#Now that the dataset is effectively cleaned with no more nulls lets save it as a csv file to do ML later
stats.to_csv("NBA_Stats.csv", index = False)